---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1xj9efvxtunaq6ry5tv92t4vjync053cw5h43arhdp98lc3gtwd7qcv3myp
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1xj9efvxtunaq6ry5tv92t4vjync053cw5h43arhdp98lc3gtwd7qcv3myp
