---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1xvxvclg889w74fckmf7q6jnf8g6pnmmczadpj3yquv0nfds2p3hqdzl9ss
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1xvxvclg889w74fckmf7q6jnf8g6pnmmczadpj3yquv0nfds2p3hqdzl9ss
