---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1ghmqmgr9ef4dndv3a97usvre0v742dxmn3274vzs0dkx0cddlgsqqj4wkr
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1ghmqmgr9ef4dndv3a97usvre0v742dxmn3274vzs0dkx0cddlgsqqj4wkr
