---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1dkw342kqw7a2xpsn68ky2qk4rpys4y02ycd0r0gcfsmgrehqp55q9j7705
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1dkw342kqw7a2xpsn68ky2qk4rpys4y02ycd0r0gcfsmgrehqp55q9j7705
