---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age18nyuvduf4yuts7wftupxhvusjjlyk6y0pwdk6vsev89xjrqqgy4sgl77en
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age18nyuvduf4yuts7wftupxhvusjjlyk6y0pwdk6vsev89xjrqqgy4sgl77en
