# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ueuCehcRyShmO4G5b+c=,iv:HVSg4BcdOJGGlMu7GDR+/xxX3B5MH2na40zps1zzi28=,tag:s/CHVc2RQfilO1cIsGcEyg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:SmXtbo/MElNxefpgdoWusBEjJGeb7Ffsle8252aSfM0w+KSDMw==,iv:NHUKEWubNnRtwrBITYrbhn5tCNBtZSZK/ld5eZQC7Yg=,tag:RccM2E/m3LR3cJY1l3V+Zw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:HMlL1f27sTgXPIbs1A84Mwzm,iv:b9s5GA9MQ7gVUmody/21Uf7Xu6gUnaBi1Rk/xpjx1ag=,tag:pU5I55cUdWMZzgPd+w9LTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkw342kqw7a2xpsn68ky2qk4rpys4y02ycd0r0gcfsmgrehqp55q9j7705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc1FlYjBTTXd3dGU0c2V3
            Rzh2L0NIZXlTelp4Z09DZDJIcEpPeENQaXdvCnFBYnM0S291VytrSGNyMDBWWTB1
            Mk14SWVyT2hoVFVQOGZoRXFsaDJka1kKLS0tIGhETTNCc1Z1aml0QlZNdUxrMjBy
            UDhWNytCajNjUnZRckhWTERSc2o2SFEKfNq5vlzMkhxXwMsTSEb86KVUsjEvGxcB
            HYBuZmu3HaSkHNqva4g9f5X6d98xNKYYaVFAJ/gbY0tUe6C+YFmjlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-17T11:28:33Z"
    mac: ENC[AES256_GCM,data:Rg4X9QAG5qKqGMKDZCLtYCH0IW8nu6iHFXrvF/xyyUgEwVdf8BSuFJSQlHFKmngvGhm81/4nS55uk28BFYuepQ3ehYdlBzMSVnNrslLlBpV+BD/UkBH0V/lESwfcCTOd6jnv6248yP3AiFhN1EofVtBtbhDGIboI79j3EZiictI=,iv:yN+cHdBPQS10lM7Ys6jhZ0o7oOVMKcfaQWGvdc3Jf2g=,tag:UK6uwtO1+sZvveUIvbBM/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
