# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OWxHXqS3hWcPxFsjBgM=,iv:alrwUhtiGTY4yM4yygcRftZ1de/xZmsmtTtbj4yXVrY=,tag:9lMkDwWKrIDRKeb/xlSc1w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:FFw2VWJl5u5k9DU74M1xEutzKCRqMBgdX9U2NOiBrwhZnOujVr53MM+06GMIUmpOHI6x8zR8yrHXVhjexppwkw==,iv:m+3vYwDpO9C8X9mDhx23evS21FnMAfWLySNZOS2AueE=,tag:tcl3iDbHUQokxu+2rVAiBA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:9TFTK3uz3kcIlvl0t9nj6lst,iv:XpJH5mDQJ4b5z/jrB+thd6bKKind4XhdRnme/LvI9VU=,tag:Ad2H4Fg2syBn9hjEbzbt5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghmqmgr9ef4dndv3a97usvre0v742dxmn3274vzs0dkx0cddlgsqqj4wkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZzJYRjFaZ3M3NzlndlFi
            Lzl1Yk53d3BHUFJUTldEczgydE1tVnN2NVVnCm9XWUtoazZvY0REdkRHQ2VWUUox
            MHVNRTgyK1JlRHRlOVJQRjFUWlAyTFEKLS0tIG9MT1VvUjVTVkJQMEdXV1pZY3RG
            dmxtZXFTNG50NVdndWl1clRpRmdCSlEKXpwc4Y5utsohswxe5Wh4/3g7hIAVr+nn
            JDZCFSFkNf56ug8CiRSD7ndykbXX5GS5iiRKcmmjdZhIwojZ/Xtcvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-12T00:37:55Z"
    mac: ENC[AES256_GCM,data:4L8bU735wZhdMhRv5BP6Dp1BrmgNqZ+exfmo22FmAvehCpbMKjUALDwifVuAtSIpg42oIshUEcXZFMuWLKFZrKl84yS5MBxiF90m7OpM7xMtilF8k+TdiFaPcLN4iC3fRrGfhkPIBL77LqLPQTWCLyPdZUQauRO8YwZrnvo/hY8=,iv:aLc1QBaOgKu/dv8esNec64x82/wahpnGS8tj132hA74=,tag:2vM2Xe/bP294+sC3FPXexQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
