# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:bh5vbRZX8SNF4bkxz+M=,iv:gcTFPG1WNj5tuycr4R+EiNzAGAym37rhCDHSI10xQdQ=,tag:WwaEOnjkKq/C1EWQTgOWEA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:gwvknMDLU33ckDlGSOAy0vmtTVwj3fUBTf9gEaAt094vK10udg==,iv:QiDC988Docjof/4sk4PuAoUSjjQF0zmG9wLOKxo6nfM=,tag:PPe1mEUYSdw/qzElx6J57Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:jIDr1EoS8tjXM5+73+R9nsyJ,iv:biawuz6y2Och/2qcGI7KjFBepP9s/5nWQt7BNEYM/KM=,tag:H3PbgOscR0yxfqXfaXxPJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkw342kqw7a2xpsn68ky2qk4rpys4y02ycd0r0gcfsmgrehqp55q9j7705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVjhDTHBoOFV0dStuNFZu
            MXBxYWlrTDdnNUd3UzBzY0w3R2p5WXJsRENNCkZReVpkVDRBQ3RkT2ZIa3lydjlX
            cUdneXJDbTZ5MGV4SjJMUGk0UERPa00KLS0tIEhNMUxSSWtQV3Bib0tJU2FIVjJl
            UzVMVmllb0lRbmVCYzhzR3hSN2pkZ1kKHe7Otc813uvOV/l1gm1dbIZqOAK68rZL
            MkwhUw8ZvZ27LFIZbTlnTeKwe3/jovL0r5My7n5FRjtIXk0PQHRk0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-17T16:48:31Z"
    mac: ENC[AES256_GCM,data:o1ts1jXVu20so0G3Woiv6XVLUaYk4Ux3OnfS0JbfyfM8SYaZ/oYs/u3JwN2troOUoeLKLq31qNvRGYvr8a1hmuN9XZw3/l7TjSe4Hdzj+HzD+7oaWoqYhdwxdIVIpmMimb5aMI3X3cuSx18jdqM5qCeYWVxylHC7RIexvCf3JkA=,iv:lrfJzTrc4AGaNUZZ3Q6Boi/0BtaC73H61aCMmaRG/D8=,tag:Q3FHfvmtjAo1MHgQRMrieg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
