# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Qv007sSC2aBGPtvE95s=,iv:tq8K0lbNM6vOoCXOCErQk4Jg2PksO54bPxGuQcENNLw=,tag:aOPqJ6CnR3lbHfbMk+t6sQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:HsTAJMw8o7FK6DiY+TM5i2ENaXeXpIpYwYLaSBkRLv2QbutlBw==,iv:l3XWr9RakZo69Oltt+CFdVQGC5OnT9J9iBZ53GOhjIU=,tag:cz1e10P+FppLChDipXx4WQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:PuE6cY5GjUo0zU9VfDwgAxgI,iv:mBRLCvGyorBjFZHSqQbNJ4AHl8XFSrgW4c7Ci+PyqIg=,tag:BnuiYJcptGAKPID+xx3E6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xj9efvxtunaq6ry5tv92t4vjync053cw5h43arhdp98lc3gtwd7qcv3myp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUDJoT3kwTVRYQ2gwTUw1
            Q1p4MGdsU1l5Qk5Nelc2MTdQcHNuUHYxYVVJCjF3dTl4ZXpmb1QyVFVCanVQcGtD
            QWhKQXVVcTBsbVNwaDYwNllUL3BVSDgKLS0tIDdncEJ1bmRQWmdVV2traTJOYld1
            dFpWUHA0TVUra2xnTW9QU2JUSUNURkEKQwP4msO8y2Mu8QbtYNtzdh0atEAP74LR
            GEvQCYFQUsS6E2KloxMIE+q530FutGVv5H3lrXK41xfXNhkccmKA4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-16T03:42:39Z"
    mac: ENC[AES256_GCM,data:GN6v06rMzf3HEvfttFtF4q+ZI3a7Ixa7OVeYNNLVFoL3Q3LzAs/bz01wn3xzWOS8mBDyfJqEm/6h1XrV+J8EhZAf68D/gXYbxjyF1+mL0Ubdn5gMhThFOIvMgEt7xdmlv6exnF/wW1GyDaC3SLpueIizWQvOOlVWDFLiRlM3VY8=,iv:Ze+0UOKvNWMmq3Y2623uFTS2TGnEqya5lMgIzqjPR2c=,tag:Kjcr//i+D3rG3kppnt4eGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
