# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:f8urLFmxDmaYDLqFK54=,iv:aX+ULErwcXeibHAI+F7R5CgO4eTpl1ME9f79apWuWuw=,tag:pbvY1DlnohR29e0kEiyd9w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:W7ThQtO2zFYYWdj1mN6m697AtEbFyPmOuZXYNFSgvLFZBDuvQA==,iv:EcEoBj6HqCUlWKyclSbDHRF38NUYD76/pOp4RqttaJI=,tag:LwvADpG3zYj969w1U5vtYQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:pBgEGwgkhqQNZl14CbQYDAY2,iv:SFVVCKvxVoPWzlgZpri/tOR1m4lZi6+PgfD0KMbCpZ4=,tag:5Yjs0AWJHqpjGpRmLjJLAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkw342kqw7a2xpsn68ky2qk4rpys4y02ycd0r0gcfsmgrehqp55q9j7705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTlljMFB5VHIzNkc2eGhN
            akhJK056R1ZEVHkzNmw3V3YyVVRHQjRFNVY4CmJ5T1hMWk9zOVVpWmJLUVRocVo1
            dEZOd1VWekFkL0JBZHpUNUJYV0xtb2sKLS0tIDkyZUp1b2tEcG1XZk4yZTNVTElk
            SGQ3NTRBNFV4RVprRVkveFBXM3hWZjAK6A4HV7Wr2BuBxFtPxvy/J0V8geeYc5cK
            2x4FKoj8jD1ZtkzD+iKAHOXQm48GxYXWzeVwMvB1Gn5kKFSNhoQffw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-17T03:22:32Z"
    mac: ENC[AES256_GCM,data:6JyWnLlcBLAwKPya4PPn3QVmjEHWmG25xNky7QB3K+jQ9qXxFnqGvxSxUua/Ln2OnPrMMDHqfhHn4Aap7aSzpVnpn357FAMzg+k3QBqYXs7VsqnUhECEK/QxPh5aA2Hlro8wgIk25DzhDT/48inGHws/tqvADGmOG6BK0HX6cmg=,iv:rIYTjh/pcw42O7ybRwLCW+jOuLirzQ1ESExwBzTJPis=,tag:0q27bK15W/AYRbnuQgt1jA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
