# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:aL4qNOrSjCUbR5hbSPg=,iv:oo+ogkJU1REBXmQbMIqW2YFxgZB2pyciej0tdkuYiCQ=,tag:4IBTosk95W/G1Hfs+8AbYw==,type:str]
    api-key: ENC[AES256_GCM,data:zYMcJvlGBEqzEyi3X5C8bl13zqOWNzCT+uVJXEEHTCj9pBy76Q==,iv:SF29XgHqmlVuzRqsFS3XmF9PJSpxYkTnCgOi75ZLIbY=,tag:fHc33JhJ32rLKB/p/ols2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkw342kqw7a2xpsn68ky2qk4rpys4y02ycd0r0gcfsmgrehqp55q9j7705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMWRRWUhQYm5MM1ZKcXpM
            R1dqMW4rK2lla0JuVjlXT3FDZUtGbTRrSFZZCnE2UTFIcWpVaDM1RTVhUE1mLy9w
            b1dEZ1NQWm8zb2lNRnZjTkF0Y2Y0RTgKLS0tIHVLYUNDRXgxWUNYOHBhU3B3azBK
            U0ZpZ3pPODZob3g2YnJuTGkvOEZ3bkUK8S0hDmYIV6tI2E2iyu0KXXU2abSNsD4h
            TmA54dH4WXHinqvTpUlA82nHwOImJaYunkyVehCxDdAIWd+B+wkeCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-17T16:48:31Z"
    mac: ENC[AES256_GCM,data:xWVm6M/vDeDQnExjriVE99MbHEoBhHm/cT+yls7fiZBErglAlM6wm+LDphMWjc+2oe4WmY1Te/LoKdUx1FJgFzOgmZDPxx1uX7y1OtsQgRm+qbwqemw1VtJLxtYVQTtgOctRkoJcKsoFrIxca8fS1UC9NEEbJrV7J/oB1hJWvxo=,iv:hKw/Z2E+aWlW8qhkQzVjXkEk23l+gorgAUnTpr2MQvc=,tag:5mzF8Z0sRUj+B7pmHm1r7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
