# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:VN1ATPwu/mnTbAgTdQ==,iv:yf7o3JI7o8l1Ur98AluAlMP413VrFLzzSEcAJNUcVrs=,tag:cd0+ib/NGrYyavgbwg/eag==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:/lBYi3XXlFuZ4wo3U9o=,iv:1joOPVVplxGlw8jPyn+14xf79ROXXRFzRxr0HLL6cWU=,tag:vypq+Hjohs4wsxk2uDZ5ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xj9efvxtunaq6ry5tv92t4vjync053cw5h43arhdp98lc3gtwd7qcv3myp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa2JrVWpGb2FQR0szZ0pp
            TFZOR0hzSk1GZXh3UXp2Mk1CVk1TNi9UUVdzCmQ4Vk1tbFJOWVV3Q2lQdlpGd3Y4
            VUgvN2YwNHU4Tm5DOTA2ZUxadlhKcnMKLS0tIDlpNGZYNlpkVS9zQWFEUzNWU0tK
            TzdCc3h2WUFKblcvUzc2NHhlNjVxdHcK9cx5cjZAAl+z9bfiMaMvuHSExdjTqQlg
            jSyP/jxT037Gm9IzX3pxF7Xk549x9YiDtxHvIs6W4kt+rvKmqgG5iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-16T03:42:39Z"
    mac: ENC[AES256_GCM,data:DQC8f2l52Qa4YegDmtGDI1+wpw4hu0TGh4aOWldHKBULl++A2LQePhiMFg1yd/uAySN/xn3KSMbKpGFGAFg4UHqreyCDdoGQ9tzf9Q7PtulzokC68PLBXcKmx5NQBAKmRYSsDaX1dzujs4aFgTcQkb58tMd/9wsOnEHdRkSFr/8=,iv:afgAWU1sInaoyD0KnNAisoY66xvYE5vx1STSRH1lUvg=,tag:jdNL59BCwOAommi0mbXtYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
