# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:K2cVUwkiTf+4S8usnQ==,iv:keisN4keiAQCO59+pwrE9oT6LvHqQOFKOvMAqV31mso=,tag:igkf5itoufP0gePdscQjHA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qIiWEZFbdnXRp8WP6Gc=,iv:mJOgTe4uipCUsgMTP9bfQQ8m2azhDOd6+fXelmYts5s=,tag:wQ/vCagAhuoybiEVo0ePaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkw342kqw7a2xpsn68ky2qk4rpys4y02ycd0r0gcfsmgrehqp55q9j7705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGRsandUemlUVjYwVUZj
            M3RMY0VDQmkxeDQvVGR6RHdObHdPTnpkUjNnCi9ObGptZk5lQVJSUHBPYldQcjBE
            SmxrZm5XMWxBVlp1SzlFRStYTjA3R2sKLS0tIHlaTXJXdU5iMkluSEJNM2lLamJm
            TFJIK2pzRDAwMUdnTFVYRllKOWJRMXMKQYtze/BsvOUMgSNjhTnVQEEeR+MT6KH9
            cgz12vd0NCyuDr8HminhRD22aJI17B89t5KzvKSmJ144bKZe5zqXuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-17T10:40:15Z"
    mac: ENC[AES256_GCM,data:JQcrZ1TQSBL3T5ti8EbsF/g/hHEJpSShEOaS9ImBLKlMeF0tDuTaPOQKiC1IGfvNsqpqQvcuCWsf/7hBzwWF5T+BDvDspJeWc/FOQaaOBOeUu3Y4Xrxkw/zPK+B/hf3u6uGl1mRZBxmzgatpGZybc3GZBPn0uZBmMCCIqqgjjlg=,iv:4i0NGYV75RV8VcqQUFqeFHeGfuc+1tjEuwRy2vEIH+4=,tag:PEqxo+0Me8Y1U3MhQYdEcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
