# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:HRcii/AjHR+zcy01GA==,iv:ojiCbtgJW/BnF+cdtHyOG7dNooFAnLQCFLOtKJsBNGE=,tag:y+BQEIjF8oV7qHW2S19tMg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:osRUttfWZSfhlOClh4o=,iv:TKbJIElJGUIk/F5thjFdH6r7MmK8RSCfL57SLYVmg7g=,tag:6OMxmRB51KIaNOYeJknrlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age155u5dfply2srmgmhhwzn7vt2sn0tvzuhu4k0wqu67rl8mjysnycq20uzu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aktTZGU4aVB0SnRzTE5S
            cFdWODhwZWRYa3FiZW1jWm55NThBSEZFRWxrCnJWaUk5SXFLQnc3bkZQY25zMmhs
            R3g2S0dBUG9JUnkrTTVXNlhKT2laT28KLS0tIDAvTVUzZVYxMHZzZXpOZWJtTXVW
            M1oxRmozOCtMSmdweWwzNzFKbDRNOVUKYWTOFx2/KQBv1zw4f+eLu3IDSYX/ZYYs
            gA161qWCfgGYDrUzWZElaMbNNTSZtiubNRlpokoiC/rqIhPx2amv2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-12T01:01:14Z"
    mac: ENC[AES256_GCM,data:Zp09EUZqy2OPL1od+JyRNBqlxRozLTEtkhTgtHEzS2NLc4jH2ZE8ULOGXdfCY0zIGK6x58i3czJc8BN9n+KpqzGaXYaWQ3+xaa7Mf+0BkbxMyiIAuLnVtObhlEEEERgNivqs9lvVkW0lKwlU3lU4bHis5BuvS219ha4dsxGKVWI=,iv:GwDd+U0XNqNqeJ4x7p7U8mLdQk6nsVChjxPMQybP3bI=,tag:tv26BzmBBt/+QlLpfmkgGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
