# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:lTJdoWL9zTytHnmiVUe/QllqfWjOAXHZs87Z6DIn/y4jkfwAhg==,iv:X8uUbHgwP3/+qJHXLLFLu/Lfa6lV04InwONnQ1tHulk=,tag:E7HRw5dqjXF4HeFRO1XMZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkw342kqw7a2xpsn68ky2qk4rpys4y02ycd0r0gcfsmgrehqp55q9j7705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNVl1SXR5UlhURjJCb2pR
            NjdoZlVzWHJaUnJYajgyZndFZ0IxUXhOTGlZCkNjMjlXN3dDRXE3UjVJZlVDbGdt
            VHVPYVNsUlZLdHh0TWtoR2dFcXY4c1UKLS0tIERVblpTQWdCcGcvYUxkSVU0RU9M
            S2p4aFczNDRlOWRTNjFSZHpQTXdyK1kKr3RW9AXLTZxYe9tUU1cvgQsh1LK6nCQz
            EZOzdwGTelGVuxQbHpEp7Jr5L8ULTq2fg9AyHAwF1NRJ1iOL30yIJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-17T04:35:22Z"
    mac: ENC[AES256_GCM,data:6JQCWCGqSbiEQyCT5zjTKViWHEMyFqrGraeKyrL+JMSjQrg6RajfnbuFWNcFOY/x5gsQR1NGlRzdGQjaJqc9IVu3xmRPub6e8/XywNA0xTriE8xc2hWPF1kdCAkoQrBh1hAvtf6Bwhbm+Lr5fOsnehy8mJRvLASz7HmOwdb8meY=,iv:pnIrqcwDWkdV2HQNjxrmvAPJCSLhpnV4/8wZIS9A+OU=,tag:YjLVCAEhDyOg2zHp26OdeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
