# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:udOZk+gJGIcZG7ZE0zo6IZTB235f+fv7UowHGXMX7fxJhx8qv9e/0FwL8Ec0Ahs+YERyssCzba1wi06l2+MqOw==,iv:1iiD/U1wvEHACMyWGftR88k7bpm7WwXG2CIbbygW/Cw=,tag:SRPI8S0cJlGnl6eDv113fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18nyuvduf4yuts7wftupxhvusjjlyk6y0pwdk6vsev89xjrqqgy4sgl77en
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRjlQMmZkcXpuRXFuaVNE
            bHJqTS9tWWFqdlRYTXVDcCtqQTViTUppcDBvCm8zZi93RFZWQ0tDcDdRVVFvMVhk
            TlJXMVVRKzArTzFwOFRnak56bnBXQmMKLS0tIElCOWp1RWQzUFNuVXdPUXpIY2tX
            b0FJUEFoTjR3MEpPdDA4a2tRMTBwY2cKiUEBSRTvFWx/4iHcQY9+8zAs30VEpDLY
            /1GB6OeiXwdZ19Z7oyl5HD9n0Sgu3AHAjDMREAvPMnxPXTnpqZsyFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-11T21:33:08Z"
    mac: ENC[AES256_GCM,data:0h+SleBTI+UR4wt/7EwPh5TRLwyAdawa2D5P8RE7QRJ4IVyjorjXSBrkDI3w/InVIVMkfJ2u/VCkjOBU+jvK4yfM9uU0IJHVxjfZzxkBgIsjvAUa7lk/qGFBZmmhwqG4YwprJTdQwAAX6VglxI+bs1xIhtf706hEfqRK97tmBi0=,iv:bQAIzHiZE4WgK55IWH+bWdC23Eb6fl7W52jzGkICdDY=,tag:NSWymu/wtuvusn6/IBRcfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
