# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:2qsFJNkALhSjBQ3A4PJMjUHZDKX4pJjiM4qhuw/qeCBp1lz8rCpwSjcAFasfYLUqRxfoJziUQYjXNUBXCFmVng==,iv:4JE9dCaA9+8/u4wgA/FcTL4CzK12ifFqxycvde/8XRg=,tag:CdTncwfU3qJWzKsg17jYTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghmqmgr9ef4dndv3a97usvre0v742dxmn3274vzs0dkx0cddlgsqqj4wkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUGpycncyZ0tTVGVORG5S
            UEJRSEJka1BITHVkcmhCWTJoZHJwcVFlZFRvCmFhNGlPdFJNaU1KYWhNdkVxaEQw
            ek9hQ1JTVTh6YkV4RnV2U25OTnQxekkKLS0tIDJFdkxNdWxJQ2JYak9DRGFrYTZL
            L29YWFA2b0RtZ0tFRDZZa1I4bmtXNUkK5VA/phgmzH8nN7e2827l9UzCDb4/6Oax
            c++l5n0If6C/DOp5Hwe35x7uENRrkMji0FesafK5yETx6dUn87odNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-12T00:37:55Z"
    mac: ENC[AES256_GCM,data:tABrlN+gTPYo5L2xLsHFiTf7851uGd9YSV9GKxwyGDOsxttD/iXpiB90lQNAhKRucABSoiNYGeMSmklKjyfXQ1HCqaADOiaiewzgNPCCrOgvKCwx1HBbhrNd9YMWzs3HCLj/SglMQcNzCCKCpXGTCQs9CK8ddoFC6CtbnO+hPbY=,iv:jkSQMK1rHvejVDN/7NgCTL9O4faxRCo6RPD9v5rKhg8=,tag:3IrKQAA821rxjDHoVShk3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
