# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:O2Nbg4RRp0dlEmX64kusmPsM2ZBkTEevgM19BcaNxRw1fZZgCw/Ogl0eibEZGjdfrWvkJOOkCeYUvs7o4jMbZA==,iv:C7B1tvo+h+mJhoWJXOTDWKSNQBVleQH6x/J5ueaznbI=,tag:+j+7vfV9IqhC9JBgV3KQyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xvxvclg889w74fckmf7q6jnf8g6pnmmczadpj3yquv0nfds2p3hqdzl9ss
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QWQ5Ylo3WjV3a2JPd0No
            clpkT0szbWhWb09HR2poczZiQWdtZU45dmprCjRKS0xWLzg2STRHMlhDdGtDaGtT
            emdFeTRBZEV1N2xRU3pBZS9ndUYrODgKLS0tIElIb09Tbnh0ZWFNclBWKzJUbWlT
            R1l2TzF5REJCaVFRcDV0ZWJHY0prN3cKe/dYVf6rhUfuJ2lA6GpbBGaFxFSzn32D
            ioeMwqgyMwYXqU/naI3jQVYE+WXDHg7aKTgJlxW/Eaq7a2xOgVHu0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-12T00:44:16Z"
    mac: ENC[AES256_GCM,data:4CzIgIxHPk+sU5CR2O2uy1tFMdM0IqZalJt+JpV48DmYzr8oNAHuSufZ1qCX1vOqt1OyDvlsHJ+8PJz5KcryWOB64UA15AjTpNwHOZIScgbjoG60dbNrcU6SKBzeQdPruvF1kGnHBR71PgOPlK2GvnUtoyxXbKb1LXQzzBhdk0w=,iv:21mHG9XtC2QlTSmL4M8p5eBiRdXZPc7jW6ft+bsRWag=,tag:THTAvyqViNvcpT1kWnv9qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
